### ISSUE TITLE
Problem with template ?

### ISSUE THREAD

**Issue by rodt974** [dickreuter/Poker#103]
Hello, 
can someone help me with this please ?
when i start the program it recognize the table then i have this problem : 

![image](https://user-images.githubusercontent.com/62392709/86442505-f973b600-bd1e-11ea-9ecc-b496f0342def.png)

**Comment by Slowly-Grokking** [comment]
I have this error too, and have tried setting up new table setups as well.

**Comment by Slowly-Grokking** [comment]
Also having trouble with this.

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "poker\main.py", line 159, in run
  File "poker\table_analysers\table_screen_based.py", line 197, in get_my_cards
  File "poker\scraper\recognize_table.py", line 57, in get_my_cards2
  File "poker\scraper\screen_operations.py", line 232, in is_template_in_search_area
  File "poker\scraper\screen_operations.py", line 222, in check_if_image_in_range
  File "poker\scraper\screen_operations.py", line 23, in find_template_on_screen
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1109: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

**Comment by dickreuter** [comment]
please try again now
