### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by fredrikburmester** [dickreuter/Poker#143]
**Describe the bug**
After installation, when starting the executable from the desktop, the program won't start and there is an error in the command line. The command line quits itself immediately so it is difficult to capture the error. Code below is manual input from a recording of the screen. 

**Screenshot png file from the log\screenshots folder**
No screenshots in the log folder. 

**Log information**
```
Traceback (most recent call last):
File "poker\main.py, line 21, in <module>
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "poker\gui\action_and_signals.py", line 27, in <module>
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "poker\scraper\table_scraper_setup_actions_and_signals.py", line 11 in <module>
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "poker\scraper\table_scraper_nn.py", line 7, in <module>
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "cv2\__init__.py", line 5 in <module>
ImportError: DLL load failed: The specified module could not be found.
[5872] Failed to execute script main
```

Running Windows 10, version: 21H1, OS Build: 19043.1165

**Comment by fredrikburmester** [comment]
This was solved by Media installing Feature Pack for Windows 10 N. It's a pack that's needed for cv2 and that is not available on N versions of Windows.
