### ISSUE TITLE
pokerbot_downloader do not work

### ISSUE THREAD

**Issue by RichardLmxhs** [dickreuter/Poker#171]
![image](https://user-images.githubusercontent.com/45809844/234194571-d080241a-3220-489d-9cbe-491fe999a889.png)
C:\Users\davidhao\Downloads>"pokerbot_downloader (2).exe"
Traceback (most recent call last):
  File "pokerbot_downloader.py", line 4, in <module>
  File "poker\tools\pokerbot_downloader_initial.py", line 34, in check_update
  File "pymongo\cursor.py", line 1207, in next
  File "pymongo\cursor.py", line 1100, in _refresh
  File "pymongo\mongo_client.py", line 1816, in _ensure_session
  File "pymongo\mongo_client.py", line 1766, in __start_session
  File "pymongo\mongo_client.py", line 1802, in _get_server_session
  File "pymongo\topology.py", line 496, in get_server_session
  File "pymongo\topology.py", line 215, in _select_servers_loop
pymongo.errors.ServerSelectionTimeoutError: Got response id 858797088 but expected 27644, Timeout: 30s, Topology Description: <TopologyDescription id: 644774c12aab3848ea39c3c6, topology_type: Single, servers: [<ServerDescription ('dickreuter.com', 27017) server_type: Unknown, rtt: None, error=ProtocolError('Got response id 858797088 but expected 27644')>]>
[14252] Failed to execute script pokerbot_downloader

i tried the newest downloader

**Comment by dickreuter** [comment]
Please delete and reinstall.
