### ISSUE TITLE
Pokerbot doesnt read my cards well (example it sees a 7d instead of 8d)

### ISSUE THREAD

**Issue by Slimbips** [dickreuter/Poker#194]
**Describe the bug**
The bot cant read my hand well, while the search area and left and right cards are good and clear images.

**Screenshot png file from the log\screenshots folder**
ss of my table: 
![ss1](https://github.com/dickreuter/Poker/assets/141335990/e9f90a5d-33f5-4214-94fd-d9cd017640cd)

ss of my cards area: 
![sscardsarea](https://github.com/dickreuter/Poker/assets/141335990/64639049-58d5-4b57-9dfc-fa377dc9c97b)

my left card: 
![leftcard](https://github.com/dickreuter/Poker/assets/141335990/d465e9c4-d220-44b2-b164-c10cf6b18f4d)

right card: 
![rightcard](https://github.com/dickreuter/Poker/assets/141335990/4936fb1c-4441-45f7-881a-ac8d8f440746)

**Log information**
INFO - Convert to Qpixmap
INFO - Update preview label
WARNING - AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
INFO - Downloading neural network weights for card recognition with tolerance...
INFO - Download complete
INFO - Is it my turn? True
1/1 [==============================] - 0s 173ms/step
1/1 [==============================] - 0s 12ms/step
INFO - My cards: ['JS', '7D']
INFO - My cards: ['JS', '7D']
Traceback (most recent call last):
  File "poker\tools\screen_operations.py", line 251, in is_template_in_search_area
  File "poker\tools\screen_operations.py", line 235, in check_if_image_in_range
  File "poker\tools\screen_operations.py", line 33, in find_template_on_screen
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "poker\scraper\table_setup_actions_and_signals.py", line 71, in <lambda>
  File "poker\scraper\table_setup_actions_and_signals.py", line 586, in test_all
  File "poker\scraper\table_scraper.py", line 115, in get_table_cards2
  File "poker\tools\screen_operations.py", line 260, in is_template_in_search_area
RuntimeError: Search area for 8d None is too small. It is 354x57 but the template is 96x78.

Greets Slim

**Comment by dickreuter** [comment]
I see, can you give me the name of the table you used for mapping?

I think you might be able to significantly improve the results if you limit the left and right card to a smaller area, so that just the J (and suit below) is visible, same for the right card. There should definitely be nothing visible of the background behind the card. 

Let me know if this helps.

**Comment by Slimbips** [comment]
the name of table i used is GGpoker v5

limitting like said i did like 100 times also with no succes..... but now i tried again and it sees my card.

LOG:

INFO - Downloading neural network weights for card recognition with tolerance...
INFO - Download complete
INFO - Is it my turn? True
1/1 [==============================] - 0s 172ms/step
1/1 [==============================] - 0s 13ms/step
INFO - My cards: ['JS', '8D']
INFO - My cards: ['JS', '8D']
Traceback (most recent call last):
  File "poker\tools\screen_operations.py", line 251, in is_template_in_search_area
  File "poker\tools\screen_operations.py", line 235, in check_if_image_in_range
  File "poker\tools\screen_operations.py", line 33, in find_template_on_screen
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "poker\scraper\table_setup_actions_and_signals.py", line 71, in <lambda>
  File "poker\scraper\table_setup_actions_and_signals.py", line 586, in test_all
  File "poker\scraper\table_scraper.py", line 115, in get_table_cards2
  File "poker\tools\screen_operations.py", line 260, in is_template_in_search_area
RuntimeError: Search area for 8d None is too small. It is 354x57 but the template is 96x78.

tested it with other cards and seems to work now :)
