### ISSUE TITLE
errors while running

### ISSUE THREAD

**Issue by shopifyusertiktok** [dickreuter/Poker#223]
INFO - Loading table scraper info for Official GGPoker 6player
WARNING - AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
INFO - Downloading neural network weights for card recognition with tolerance...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "poker\main.py", line 164, in run
  File "poker\tools\mongo_manager.py", line 81, in load_table_nn_weights
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jnortheastfilms** [comment]
Hi, I'm getting a similar issue:

```
Successfully created the directory 'Log'
Successfully created the directory 'log/pics'
Saving log file to: log\deepmind_pokerbot.log
Saving info file to: log\deepmind_pokerbot_info.log
Saving error only file to: log\deepmind_pokerbot_errors.log
INFO - Initializing program
INFO - Check for auto-update
Traceback (most recent call last):
File "requests ([models.py](http://models.py/)" line
File "json\ init__.py'
Line 346,
in json
Loads
File "json\[decoder.py](http://decoder.py/)", Line 337, in decode
File "json\[decoder.py](http://decoder.py/)", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "poker\[main.py](http://main.py/)", line 327, in <module>
File "poker\[main.py](http://main.py/)", line 288, in run_poker
File "poker\tools\[update_checker.py](http://update_checker.py/)", line 41, in check_update
File "requests\[models.py](http://models.py/)", line 975, in json
reguests.exceptions.JSONDecodeError: Expecting value: line 1 column I (char 0)
[23796] Failed to execute script 'main' due to unhandled exception!
```

Any ideas?
