### ISSUE TITLE
Program won't run

### ISSUE THREAD

**Issue by jnortheastfilms** [dickreuter/Poker#232]
After opening the exe, I'm left with this error in the terminal screen :

```
Successfully created the directory 'Log'
Successfully created the directory 'log/pics'
Saving log file to: log\deepmind_pokerbot.log
Saving info file to: log\deepmind_pokerbot_info.log
Saving error only file to: log\deepmind_pokerbot_errors.log
INFO - Initializing program
INFO - Check for auto-update
Traceback (most recent call last):
File "requests ([models.py](http://models.py/)" line
File "json\ init__.py'
Line 346,
in json
Loads
File "json\[decoder.py](http://decoder.py/)", Line 337, in decode
File "json\[decoder.py](http://decoder.py/)", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "poker\[main.py](http://main.py/)", line 327, in <module>
File "poker\[main.py](http://main.py/)", line 288, in run_poker
File "poker\tools\[update_checker.py](http://update_checker.py/)", line 41, in check_update
File "requests\[models.py](http://models.py/)", line 975, in json
reguests.exceptions.JSONDecodeError: Expecting value: line 1 column I (char 0)
[23796] Failed to execute script 'main' due to unhandled exception!
```

**Comment by dickreuter** [comment]
sever has been restarted.
