### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by stephanMettler** [dickreuter/Poker#35]
ubuntu:

```
sudo apt-get install python-pyqt5 python-xlib python-opencv
python -m pip install pandas pymongo configobj pymouse captcha xlrd

git clone https://github.com/dickreuter/Poker.git
cd Poker
python main.py
```

gives me the error:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from decisionmaker.decisionmaker import *
ImportError: No module named decisionmaker.decisionmaker
```

When uncommenting following line from main.py
```
from decisionmaker.decisionmaker import *
```

it get:

```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from tools.mouse_mover import *
  File "/home/rebien/Documents/pokerimager/Poker2/tools/mouse_mover.py", line 8, in <module>
    from captcha.key_press_vbox import *
ImportError: No module named key_press_vbox

```

**Comment by dickreuter** [comment]
This is a different setup than described in the wiki. Please follow the
instructions in the wiki and install anaconda and my fork of pyuserinout
etc.
