### ISSUE TITLE
Mongodb install

### ISSUE THREAD

**Issue by Tjorriemorrie** [dickreuter/Poker#43]
`
>Pokerbot_downloader.exe
Traceback (most recent call last):
  File "Pokerbot_downloader.py", line 42, in <module>
  File "Pokerbot_downloader.py", line 33, in check_update
  File "site-packages\pymongo\cursor.py", line 1090, in next
  File "site-packages\pymongo\cursor.py", line 1012, in _refresh
  File "site-packages\pymongo\cursor.py", line 850, in __send_message
  File "site-packages\pymongo\mongo_client.py", line 798, in _send_message_with_
response
  File "site-packages\pymongo\mongo_client.py", line 809, in _reset_on_error
  File "site-packages\pymongo\server.py", line 88, in send_message_with_response

  File "contextlib.py", line 59, in __enter__
  File "site-packages\pymongo\server.py", line 152, in get_socket
  File "contextlib.py", line 59, in __enter__
  File "site-packages\pymongo\pool.py", line 541, in get_socket
  File "site-packages\pymongo\pool.py", line 306, in check_auth
  File "site-packages\pymongo\auth.py", line 436, in authenticate
  File "site-packages\pymongo\auth.py", line 416, in _authenticate_default
  File "site-packages\pymongo\auth.py", line 188, in _authenticate_scram_sha1
  File "site-packages\pymongo\pool.py", line 213, in command
  File "site-packages\pymongo\network.py", line 99, in command
  File "site-packages\pymongo\helpers.py", line 196, in _check_command_response
pymongo.errors.OperationFailure: Authentication failed.
Failed to execute script Pokerbot_downloader
`

**Comment by Tjorriemorrie** [comment]
Why is this hardcoded like that?

`        self.mongoclient = MongoClient('mongodb://guest:donald@52.201.173.151:27017/POKER')`

**Comment by dickreuter** [comment]
I agree it shouldn't be. Any better suggestions?

**Comment by Tjorriemorrie** [comment]
Normally configuration generation. But I don't think that is suitable for this. I'll change it to env variables, then your defaults are preserved and allowing overwriting. If I come right I'll do a PR. 

All that is needed is just a plain mongodb connection?

**Comment by dickreuter** [comment]
Yes. Ideally we would create a restful interface and then the public code
will only connect to that but that's probably too much of a hassle.

With env variables you mean an external config file?

**Comment by Tjorriemorrie** [comment]
Is the mongodb server hosted on another server?

This doesn't make sense
```
    def check_update(self, version):
        cursor = self.mongodb.internal.find()
        c = cursor.next()
        current_version = c['current_version']
        self.dl_link = c['dl']
        latest_updates = c['latest_updates']
        if current_version > version:
```

and `cursor.next` gives StopIteration error because there's obviously no rows in mongo. How is this supposed to work?

**Comment by dickreuter** [comment]
No it's on the same server. Just a different collection. Do you get the
same error when running the binaries?

**Comment by dickreuter** [comment]
Fixed the server
