### ISSUE TITLE
monogodb connection error

### ISSUE THREAD

**Issue by matthewgroves** [dickreuter/Poker#76]
Is there a problem with the mongodb server?

Traceback (most recent call last):
  File "poker\main.py", line 301, in <module>
    run_poker()
  File "poker\main.py", line 247, in run_poker
    u.check_update(version)
  File "C:\Users\Matt\Desktop\Poker-master\poker\tools\mongo_manager.py", line 45, in check_update
    c = cursor.next()
  File "C:\Users\Matt\Anaconda3\envs\poker_venv\lib\site-packages\pymongo\cursor.py", line 1132, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Matt\Anaconda3\envs\poker_venv\lib\site-packages\pymongo\cursor.py", line 1055, in _refresh
    self.__collation))
  File "C:\Users\Matt\Anaconda3\envs\poker_venv\lib\site-packages\pymongo\cursor.py", line 892, in __send_message
    **kwargs)
  File "C:\Users\Matt\Anaconda3\envs\poker_venv\lib\site-packages\pymongo\mongo_client.py", line 933, in _send_message_with_response
    server = topology.select_server(selector)
  File "C:\Users\Matt\Anaconda3\envs\poker_venv\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "C:\Users\Matt\Anaconda3\envs\poker_venv\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: dickreuter.com:27017: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by dickreuter** [comment]
try now. What tables are you playing on?

**Comment by matthewgroves** [comment]
working now thanks. I'm currently trying to update to work on current PS zoom tables

**Comment by dickreuter** [comment]
ok that's great. Can you commit and push your changes?

**Comment by YazzyYaz** [comment]
Hi, can we reopen this issue as I'm hitting it as I'm trying to install the binary.

**Comment by willcollie1** [comment]
Hi, I am also hitting the following issue when running main.py.
